# Generated by Django 3.0.7 on 2020-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilegeek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='about_topic',
            field=models.TextField(),
        ),
    ]
